/**
 * Independent differential validation of the lunisolar calendar against cnlunar
 * (https://github.com/OPN48/cnlunar), a third-party Python implementation of the
 * Chinese calendar. The fixture's answer key is authored by cnlunar, not by us,
 * so this is a tier-1 external check (not a self-consistent round-trip).
 *
 * Fixture generated by scripts/gen-cnlunar-fixture.py — see tests/fixtures/README.md.
 */
import { describe, it, expect } from 'vitest';
import { gregorianToLunisolar } from '../src/lunisolar-calendar';
import fixtures from './fixtures/cnlunar-lunisolar.json';

type Entry = { g: [number, number, number]; l: [number, number]; leap: boolean };

describe('Cross-validation: lunisolar calendar (農曆) vs cnlunar', () => {
  it(`matches cnlunar month/day/leap for all ${(fixtures as Entry[]).length} dates`, () => {
    const mismatches: string[] = [];
    for (const { g, l, leap } of fixtures as Entry[]) {
      const [y, m, d] = g;
      const r = gregorianToLunisolar(new Date(y, m - 1, d));
      if (r.month !== l[0] || r.day !== l[1] || r.isLeapMonth !== leap) {
        mismatches.push(
          `${y}-${m}-${d}: got M${r.month}${r.isLeapMonth ? '(leap)' : ''} D${r.day}, ` +
            `cnlunar M${l[0]}${leap ? '(leap)' : ''} D${l[1]}`,
        );
      }
    }
    // Show the first few mismatches in the failure message, then assert none.
    expect(mismatches.slice(0, 20)).toEqual([]);
    expect(mismatches.length).toBe(0);
  });
});
