/**
 * Moon position validation via lunar phase timing.
 *
 * At new moon, the Sun-Moon ecliptic longitude difference ≈ 0°.
 * At full moon, the difference ≈ 180°. If our Moon and Sun ephemerides
 * are accurate, the elongation at JPL-derived phase times should be
 * very close to 0° or 180°.
 *
 * Fixture data generated by scripts/generate-lunar-fixtures.mjs.
 * JPL reference: Moon (301) and Sun (10) apparent RA/Dec at 6-hour step,
 * phase crossing times interpolated from ecliptic longitude elongation.
 */

import { describe, it, expect } from 'vitest';
import { getMoonPosition } from '../src/index';
import { getSunLongitude } from '../src/solar-longitude';
import lunarPhaseFixtures from './fixtures/jpl-lunar-phases.json';

interface LunarPhaseRef {
  type: 'new' | 'full';
  dateISO: string;
  timestamp: number;
}

describe('lunar phase timing validation vs JPL', () => {
  const refs = lunarPhaseFixtures as LunarPhaseRef[];

  it('has at least 100 reference phases', () => {
    expect(refs.length).toBeGreaterThanOrEqual(100);
  });

  it('Moon longitude matches Sun at new moons (within 1°)', () => {
    const newMoons = refs.filter(r => r.type === 'new');
    expect(newMoons.length).toBeGreaterThan(0);
    const errors: number[] = [];
    for (const ref of newMoons) {
      const date = new Date(ref.timestamp);
      const moon = getMoonPosition(date);
      const sun = getSunLongitude(date);
      let diff = Math.abs(moon.longitude - sun);
      if (diff > 180) diff = 360 - diff;
      errors.push(diff);
      expect(diff, `new moon ${ref.dateISO}: elongation ${diff.toFixed(3)}°`).toBeLessThan(1);
    }
    const mean = errors.reduce((a, b) => a + b, 0) / errors.length;
    // Mean elongation at new moon should be very small (< 0.3°)
    expect(mean).toBeLessThan(0.3);
  });

  it('Moon longitude opposes Sun at full moons (within 1°)', () => {
    const fullMoons = refs.filter(r => r.type === 'full');
    expect(fullMoons.length).toBeGreaterThan(0);
    const errors: number[] = [];
    for (const ref of fullMoons) {
      const date = new Date(ref.timestamp);
      const moon = getMoonPosition(date);
      const sun = getSunLongitude(date);
      let diff = Math.abs(moon.longitude - sun);
      if (diff > 180) diff = 360 - diff;
      // At full moon, elongation should be near 180°
      const err = Math.abs(diff - 180);
      errors.push(err);
      expect(err, `full moon ${ref.dateISO}: elongation ${diff.toFixed(3)}°`).toBeLessThan(1);
    }
    const mean = errors.reduce((a, b) => a + b, 0) / errors.length;
    expect(mean).toBeLessThan(0.3);
  });
});
