/**
 * 4-way planet position validation: stem-branch vs JPL DE441 vs Swiss Ephemeris.
 *
 * Compares getPlanetPosition() ecliptic longitude and latitude against:
 * 1. JPL Horizons DE441 (ground truth — numerical integration)
 * 2. Swiss Ephemeris Moshier (independent analytical ephemeris)
 *
 * Fixture data generated by scripts/generate-planet-fixtures.mjs (JPL)
 * and scripts/generate-sweph-fixtures.mjs (Swiss Ephemeris).
 *
 * Accuracy thresholds calibrated against observed residuals (1900-2100):
 * - Inner planets (Mercury, Venus): mean ~1-2", max ~6" — excellent
 * - Outer planets (Mars–Neptune): mean ~11-14", max ~23-29" — VSOP87D truncation
 * - Pluto (Meeus Ch. 37): mean ~2569" (~0.71°) — low-precision algorithm
 * - Swiss Ephemeris vs JPL: ~0.3" mean — confirms JPL as reliable ground truth
 */

import { describe, it, expect } from 'vitest';
import { getPlanetPosition } from '../src/index';
import type { Planet } from '../src/types';
import jplFixtures from './fixtures/jpl-planet-positions.json';
import sweFixtures from './fixtures/sweph-planet-positions.json';

interface PlanetRef {
  planet: string;
  dateISO: string;
  timestamp: number;
  eclLon: number;
  eclLat: number;
}

// Accuracy thresholds (arcseconds) — calibrated to observed residuals with ~50% margin.
// Observed (1900-2100, 101 epochs each, 730-day step):
//   Mercury: mean 1.16", max 6.38"  |  Venus: mean 2.29", max 6.35"
//   Mars: mean 11.09", max 29.18"   |  Jupiter: mean 13.03", max 23.28"
//   Saturn: mean 13.22", max 22.51" |  Uranus: mean 13.55", max 22.82"
//   Neptune: mean 12.76", max 22.58"|  Pluto: mean 2569", max 5178"
const THRESHOLDS: Record<string, { meanMax: number; absMax: number }> = {
  mercury: { meanMax: 3,    absMax: 10 },
  venus:   { meanMax: 5,    absMax: 10 },
  mars:    { meanMax: 16,   absMax: 40 },
  jupiter: { meanMax: 18,   absMax: 30 },
  saturn:  { meanMax: 18,   absMax: 30 },
  uranus:  { meanMax: 18,   absMax: 30 },
  neptune: { meanMax: 18,   absMax: 30 },
  pluto:   { meanMax: 3500, absMax: 7000 },
};

describe('planet position validation vs JPL DE441', () => {
  const refs = jplFixtures as PlanetRef[];

  it('has reference data for all planets', () => {
    const planets = new Set(refs.map(r => r.planet));
    for (const p of Object.keys(THRESHOLDS)) {
      expect(planets.has(p), `missing reference data for ${p}`).toBe(true);
    }
  });

  for (const [planet, threshold] of Object.entries(THRESHOLDS)) {
    describe(planet, () => {
      const planetRefs = refs.filter(r => r.planet === planet);

      it('has at least 20 reference epochs', () => {
        expect(planetRefs.length).toBeGreaterThanOrEqual(20);
      });

      it(`mean |ΔL| < ${threshold.meanMax}" vs JPL`, () => {
        const errors: number[] = [];
        for (const ref of planetRefs) {
          const date = new Date(ref.timestamp);
          const pos = getPlanetPosition(planet as Planet, date);
          let diff = pos.longitude - ref.eclLon;
          if (diff > 180) diff -= 360;
          if (diff < -180) diff += 360;
          errors.push(Math.abs(diff) * 3600);
        }
        const mean = errors.reduce((a, b) => a + b, 0) / errors.length;
        expect(mean).toBeLessThan(threshold.meanMax);
      });

      it(`max |ΔL| < ${threshold.absMax}" vs JPL`, () => {
        let maxErr = 0;
        for (const ref of planetRefs) {
          const date = new Date(ref.timestamp);
          const pos = getPlanetPosition(planet as Planet, date);
          let diff = pos.longitude - ref.eclLon;
          if (diff > 180) diff -= 360;
          if (diff < -180) diff += 360;
          maxErr = Math.max(maxErr, Math.abs(diff) * 3600);
        }
        expect(maxErr).toBeLessThan(threshold.absMax);
      });

      it(`latitude |Δβ| < ${threshold.absMax * 2}" vs JPL`, () => {
        let maxErr = 0;
        for (const ref of planetRefs) {
          const date = new Date(ref.timestamp);
          const pos = getPlanetPosition(planet as Planet, date);
          const diff = Math.abs(pos.latitude - ref.eclLat) * 3600;
          maxErr = Math.max(maxErr, diff);
        }
        expect(maxErr).toBeLessThan(threshold.absMax * 2);
      });
    });
  }
});

describe('Swiss Ephemeris cross-validation', () => {
  const sweRefs = sweFixtures as PlanetRef[];
  const jplRefs = jplFixtures as PlanetRef[];

  it('Swiss Ephemeris agrees with JPL to < 3" for all VSOP87D planets', () => {
    const vsopPlanets = ['mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune'];
    for (const planet of vsopPlanets) {
      const sweForPlanet = sweRefs.filter(r => r.planet === planet);
      const jplMap = new Map(jplRefs.filter(r => r.planet === planet).map(r => [r.timestamp, r]));
      for (const swe of sweForPlanet) {
        const jpl = jplMap.get(swe.timestamp);
        if (!jpl) continue;
        let diff = swe.eclLon - jpl.eclLon;
        if (diff > 180) diff -= 360;
        if (diff < -180) diff += 360;
        expect(
          Math.abs(diff) * 3600,
          `${planet} ${swe.dateISO}: SwEph vs JPL`,
        ).toBeLessThan(3);
      }
    }
  });

  it('stem-branch vs SwEph errors match stem-branch vs JPL errors (±2")', () => {
    // If SwEph ≈ JPL, then SB-vs-SwEph ≈ SB-vs-JPL. This confirms consistency.
    const vsopPlanets = ['mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune'];
    for (const planet of vsopPlanets) {
      const sweForPlanet = sweRefs.filter(r => r.planet === planet);
      const jplMap = new Map(jplRefs.filter(r => r.planet === planet).map(r => [r.timestamp, r]));
      const sbVsJpl: number[] = [];
      const sbVsSwe: number[] = [];
      for (const swe of sweForPlanet) {
        const jpl = jplMap.get(swe.timestamp);
        if (!jpl) continue;
        const date = new Date(swe.timestamp);
        const pos = getPlanetPosition(planet as Planet, date);
        let dJpl = pos.longitude - jpl.eclLon;
        if (dJpl > 180) dJpl -= 360;
        if (dJpl < -180) dJpl += 360;
        sbVsJpl.push(Math.abs(dJpl) * 3600);
        let dSwe = pos.longitude - swe.eclLon;
        if (dSwe > 180) dSwe -= 360;
        if (dSwe < -180) dSwe += 360;
        sbVsSwe.push(Math.abs(dSwe) * 3600);
      }
      const meanJpl = sbVsJpl.reduce((a, b) => a + b, 0) / sbVsJpl.length;
      const meanSwe = sbVsSwe.reduce((a, b) => a + b, 0) / sbVsSwe.length;
      expect(
        Math.abs(meanJpl - meanSwe),
        `${planet}: SB-vs-JPL mean (${meanJpl.toFixed(2)}) ≈ SB-vs-SwE mean (${meanSwe.toFixed(2)})`,
      ).toBeLessThan(2);
    }
  });
});
